"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
import dj_database_url

# =====================
# Paths base
# =====================
BASE_DIR = Path(__file__).resolve().parent.parent

# =====================
# Seguridad / modo dev
# =====================

# Se lee de variables de entorno en Render
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-4%0#kf-7(8d-9=370^zqf1f^(4@0rzmw$1^wvtje*1se*m-er%",
)

# Render envía DEBUG="False"
DEBUG = os.environ.get("DEBUG", "True") == "True"

# ALLOWED_HOSTS dinámico
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")

# Si está vacío (en local), usa localhost
if not ALLOWED_HOSTS or ALLOWED_HOSTS == [""]:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Necesario para que Django acepte requests desde Render
CSRF_TRUSTED_ORIGINS = [
    "https://mibio.onrender.com",
    "https://*.onrender.com",
]

# =====================
# Apps instaladas
# =====================
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Apps del proyecto
    "vcards",
    "folders",
    "users",
    "dashboard",
]

# =====================
# Middleware
# =====================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# =====================
# Templates
# =====================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# =====================
# Base de datos (Postgres en Render / local)
# =====================
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True,
    )
}

# =====================
# Password validators
# =====================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =====================
# i18n
# =====================
LANGUAGE_CODE = "es-mx"
TIME_ZONE = "America/Mexico_City"
USE_I18N = True
USE_TZ = True

# =====================
# Static files
# =====================
STATIC_URL = "static/"

# Donde Render guardará los archivos compilados
STATIC_ROOT = BASE_DIR / "staticfiles"

# Solo para desarrollo (si tienes carpeta static/)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# =====================
# Auth custom
# =====================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.User"
LOGIN_URL = "users:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "users:login"
