"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""
import os
import dj_database_url
from pathlib import Path

# --- Paths base ---
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Seguridad / modo dev ---
# Usa la SECRET_KEY del entorno, y si no existe usa la de desarrollo
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-4%0#kf-7(8d-9=370^zqf1f^(4@0rzmw$1^wvtje*1se*m-er%"
)

# DEBUG desde env (en Render pones False)
DEBUG = os.environ.get("DEBUG", "True") == "True"

# ALLOWED_HOSTS desde env: ".onrender.com,localhost,127.0.0.1"
allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "")
if allowed_hosts_env:
    ALLOWED_HOSTS: list[str] = [h.strip() for h in allowed_hosts_env.split(",")]
else:
    ALLOWED_HOSTS: list[str] = []

# --- Apps ---
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Apps del proyecto
    "vcards",
    "folders",
    "users",
    "dashboard",
]
...
# --- Static ---
STATIC_URL = "static/"

# carpeta donde collectstatic va a dejar todos los archivos para producción
STATIC_ROOT = BASE_DIR / "staticfiles"

# importante: apunta a la carpeta 'static' de la raíz del proyecto (para desarrollo)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
...
# --- Auth custom ---
AUTH_USER_MODEL = "users.User"
LOGIN_URL = "users:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "users:login"
